'use strict';

export const countryAliases = {
    "Congo (Brazzaville)": "Congo",
    "Congo (Kinshasa)": "DR Congo",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Czechia": "Czech Republic (Czechia)",
    "Korea, South": "South Korea",
    "Saint Kitts and Nevis": "Saint Kitts & Nevis",
    "Saint Vincent and the Grenadines": "St. Vincent & Grenadines",
    "Sao Tome and Principe": "Sao Tome & Principe",
    "Taiwan*": "Taiwan",
    "US": "United States",
    "West Bank and Gaza": "State of Palestine",
};

// https://www.worldometers.info/world-population/population-by-country/
const populationByCountryRaw = [
    { name: "Afghanistan", count: 38928346 },
    { name: "Albania", count: 2877797 },
    { name: "Algeria", count: 43851044 },
    { name: "American Samoa", count: 55191 },
    { name: "Andorra", count: 77265 },
    { name: "Angola", count: 32866272 },
    { name: "Anguilla", count: 15003 },
    { name: "Antigua and Barbuda", count: 97929 },
    { name: "Argentina", count: 45195774 },
    { name: "Armenia", count: 2963243 },
    { name: "Aruba", count: 106766 },
    { name: "Australia", count: 25499884 },
    { name: "Austria", count: 9006398 },
    { name: "Azerbaijan", count: 10139177 },
    { name: "Bahamas", count: 393244 },
    { name: "Bahrain", count: 1701575 },
    { name: "Bangladesh", count: 164689383 },
    { name: "Barbados", count: 287375 },
    { name: "Belarus", count: 9449323 },
    { name: "Belgium", count: 11589623 },
    { name: "Belize", count: 397628 },
    { name: "Benin", count: 12123200 },
    { name: "Bermuda", count: 62278 },
    { name: "Bhutan", count: 771608 },
    { name: "Bolivia", count: 11673021 },
    { name: "Bosnia and Herzegovina", count: 3280819 },
    { name: "Botswana", count: 2351627 },
    { name: "Brazil", count: 212559417 },
    { name: "British Virgin Islands", count: 30231 },
    { name: "Brunei", count: 437479 },
    { name: "Bulgaria", count: 6948445 },
    { name: "Burkina Faso", count: 20903273 },
    { name: "Burundi", count: 11890784 },
    { name: "Cabo Verde", count: 555987 },
    { name: "Cambodia", count: 16718965 },
    { name: "Cameroon", count: 26545863 },
    { name: "Canada", count: 37742154 },
    { name: "Caribbean Netherlands", count: 26223 },
    { name: "Cayman Islands", count: 65722 },
    { name: "Central African Republic", count: 4829767 },
    { name: "Chad", count: 16425864 },
    { name: "Channel Islands", count: 173863 },
    { name: "Chile", count: 19116201 },
    { name: "China", count: 1439323776 },
    { name: "Colombia", count: 50882891 },
    { name: "Comoros", count: 869601 },
    { name: "Congo", count: 5518087 },
    { name: "Cook Islands", count: 17564 },
    { name: "Costa Rica", count: 5094118 },
    { name: "Côte d'Ivoire", count: 26378274 },
    { name: "Croatia", count: 4105267 },
    { name: "Cuba", count: 11326616 },
    { name: "Curaçao", count: 164093 },
    { name: "Cyprus", count: 1207359 },
    { name: "Czech Republic (Czechia)", count: 10708981 },
    { name: "Denmark", count: 5792202 },
    { name: "Djibouti", count: 988000 },
    { name: "Dominica", count: 71986 },
    { name: "Dominican Republic", count: 10847910 },
    { name: "DR Congo", count: 89561403 },
    { name: "Ecuador", count: 17643054 },
    { name: "Egypt", count: 102334404 },
    { name: "El Salvador", count: 6486205 },
    { name: "Equatorial Guinea", count: 1402985 },
    { name: "Eritrea", count: 3546421 },
    { name: "Estonia", count: 1326535 },
    { name: "Eswatini", count: 1160164 },
    { name: "Ethiopia", count: 114963588 },
    { name: "Faeroe Islands", count: 48863 },
    { name: "Falkland Islands", count: 3480 },
    { name: "Fiji", count: 896445 },
    { name: "Finland", count: 5540720 },
    { name: "France", count: 65273511 },
    { name: "French Guiana", count: 298682 },
    { name: "French Polynesia", count: 280908 },
    { name: "Gabon", count: 2225734 },
    { name: "Gambia", count: 2416668 },
    { name: "Georgia", count: 3989167 },
    { name: "Germany", count: 83783942 },
    { name: "Ghana", count: 31072940 },
    { name: "Gibraltar", count: 33691 },
    { name: "Greece", count: 10423054 },
    { name: "Greenland", count: 56770 },
    { name: "Grenada", count: 112523 },
    { name: "Guadeloupe", count: 400124 },
    { name: "Guam", count: 168775 },
    { name: "Guatemala", count: 17915568 },
    { name: "Guinea-Bissau", count: 1968001 },
    { name: "Guinea", count: 13132795 },
    { name: "Guyana", count: 786552 },
    { name: "Haiti", count: 11402528 },
    { name: "Holy See", count: 801 },
    { name: "Honduras", count: 9904607 },
    { name: "Hong Kong", count: 7496981 },
    { name: "Hungary", count: 9660351 },
    { name: "Iceland", count: 341243 },
    { name: "India", count: 1380004385 },
    { name: "Indonesia", count: 273523615 },
    { name: "Iran", count: 83992949 },
    { name: "Iraq", count: 40222493 },
    { name: "Ireland", count: 4937786 },
    { name: "Isle of Man", count: 85033 },
    { name: "Israel", count: 8655535 },
    { name: "Italy", count: 60461826 },
    { name: "Jamaica", count: 2961167 },
    { name: "Japan", count: 126476461 },
    { name: "Jordan", count: 10203134 },
    { name: "Kazakhstan", count: 18776707 },
    { name: "Kenya", count: 53771296 },
    { name: "Kiribati", count: 119449 },
    { name: "Kuwait", count: 4270571 },
    { name: "Kyrgyzstan", count: 6524195 },
    { name: "Laos", count: 7275560 },
    { name: "Latvia", count: 1886198 },
    { name: "Lebanon", count: 6825445 },
    { name: "Lesotho", count: 2142249 },
    { name: "Liberia", count: 5057681 },
    { name: "Libya", count: 6871292 },
    { name: "Liechtenstein", count: 38128 },
    { name: "Lithuania", count: 2722289 },
    { name: "Luxembourg", count: 625978 },
    { name: "Macao", count: 649335 },
    { name: "Madagascar", count: 27691018 },
    { name: "Malawi", count: 19129952 },
    { name: "Malaysia", count: 32365999 },
    { name: "Maldives", count: 540544 },
    { name: "Mali", count: 20250833 },
    { name: "Malta", count: 441543 },
    { name: "Marshall Islands", count: 59190 },
    { name: "Martinique", count: 375265 },
    { name: "Mauritania", count: 4649658 },
    { name: "Mauritius", count: 1271768 },
    { name: "Mayotte", count: 272815 },
    { name: "Mexico", count: 128932753 },
    { name: "Micronesia", count: 115023 },
    { name: "Moldova", count: 4033963 },
    { name: "Monaco", count: 39242 },
    { name: "Mongolia", count: 3278290 },
    { name: "Montenegro", count: 628066 },
    { name: "Montserrat", count: 4992 },
    { name: "Morocco", count: 36910560 },
    { name: "Mozambique", count: 31255435 },
    /* { name: "Myanmar", count: 54409800 }, */
    { name: "Namibia", count: 2540905 },
    { name: "Nauru", count: 10824 },
    { name: "Nepal", count: 29136808 },
    { name: "Netherlands", count: 17134872 },
    { name: "New Caledonia", count: 285498 },
    { name: "New Zealand", count: 4822233 },
    { name: "Nicaragua", count: 6624554 },
    { name: "Niger", count: 24206644 },
    { name: "Nigeria", count: 206139589 },
    { name: "Niue", count: 1626 },
    { name: "North Korea", count: 25778816 },
    { name: "North Macedonia", count: 2083374 },
    { name: "Northern Mariana Islands", count: 57559 },
    { name: "Norway", count: 5421241 },
    { name: "Oman", count: 5106626 },
    { name: "Pakistan", count: 220892340 },
    { name: "Palau", count: 18094 },
    { name: "Panama", count: 4314767 },
    { name: "Papua New Guinea", count: 8947024 },
    { name: "Paraguay", count: 7132538 },
    { name: "Peru", count: 32971854 },
    { name: "Philippines", count: 109581078 },
    { name: "Poland", count: 37846611 },
    { name: "Portugal", count: 10196709 },
    { name: "Puerto Rico", count: 2860853 },
    { name: "Qatar", count: 2881053 },
    { name: "Réunion", count: 895312 },
    { name: "Romania", count: 19237691 },
    { name: "Russia", count: 145934462 },
    { name: "Rwanda", count: 12952218 },
    { name: "Saint Barthelemy", count: 9877 },
    { name: "Saint Helena", count: 6077 },
    { name: "Saint Kitts & Nevis", count: 53199 },
    { name: "Saint Lucia", count: 183627 },
    { name: "Saint Martin", count: 38666 },
    { name: "Saint Pierre & Miquelon", count: 5794 },
    { name: "Samoa", count: 198414 },
    { name: "San Marino", count: 33931 },
    { name: "Sao Tome & Principe", count: 219159 },
    { name: "Saudi Arabia", count: 34813871 },
    { name: "Senegal", count: 16743927 },
    { name: "Serbia", count: 8737371 },
    { name: "Seychelles", count: 98347 },
    { name: "Sierra Leone", count: 7976983 },
    { name: "Singapore", count: 5850342 },
    { name: "Sint Maarten", count: 42876 },
    { name: "Slovakia", count: 5459642 },
    { name: "Slovenia", count: 2078938 },
    { name: "Solomon Islands", count: 686884 },
    { name: "Somalia", count: 15893222 },
    { name: "South Africa", count: 59308690 },
    { name: "South Korea", count: 51269185 },
    { name: "South Sudan", count: 11193725 },
    { name: "Spain", count: 46754778 },
    { name: "Sri Lanka", count: 21413249 },
    { name: "St. Vincent & Grenadines", count: 110940 },
    { name: "State of Palestine", count: 5101414 },
    { name: "Sudan", count: 43849260 },
    { name: "Suriname", count: 586632 },
    { name: "Sweden", count: 10099265 },
    { name: "Switzerland", count: 8654622 },
    { name: "Syria", count: 17500658 },
    { name: "Taiwan", count: 23816775 },
    { name: "Tajikistan", count: 9537645 },
    { name: "Tanzania", count: 59734218 },
    { name: "Thailand", count: 69799978 },
    { name: "Timor-Leste", count: 1318445 },
    { name: "Togo", count: 8278724 },
    { name: "Tokelau", count: 1357 },
    { name: "Tonga", count: 105695 },
    { name: "Trinidad and Tobago", count: 1399488 },
    { name: "Tunisia", count: 11818619 },
    { name: "Turkey", count: 84339067 },
    { name: "Turkmenistan", count: 6031200 },
    { name: "Turks and Caicos", count: 38717 },
    { name: "Tuvalu", count: 11792 },
    { name: "U.S. Virgin Islands", count: 104425 },
    { name: "Uganda", count: 45741007 },
    { name: "Ukraine", count: 43733762 },
    { name: "United Arab Emirates", count: 9890402 },
    { name: "United Kingdom", count: 67886011 },
    { name: "United States", count: 331002651 },
    { name: "Uruguay", count: 3473730 },
    { name: "Uzbekistan", count: 33469203 },
    { name: "Vanuatu", count: 307145 },
    { name: "Venezuela", count: 28435940 },
    { name: "Vietnam", count: 97338579 },
    { name: "Wallis & Futuna", count: 11239 },
    { name: "Western Sahara", count: 597339 },
    { name: "Yemen", count: 29825964 },
    { name: "Zambia", count: 18383955 },
    { name: "Zimbabwe", count: 14862924 }
];
populationByCountryRaw.push({ name: "Kosovo", count: 1810366, code: "XK" }); // https://en.wikipedia.org/wiki/Demographics_of_Kosovo
populationByCountryRaw.push({ name: "Burma", count: 54409800, code: "MM" }); // copied from Myanmar above

// https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/slim-2/slim-2.json
const countrieswithRegionalCodes = [
    { "name": "Afghanistan", "alpha-2": "AF", "country-code": "004" },
    { "name": "Åland Islands", "alpha-2": "AX", "country-code": "248" },
    { "name": "Albania", "alpha-2": "AL", "country-code": "008" },
    { "name": "Algeria", "alpha-2": "DZ", "country-code": "012" },
    { "name": "American Samoa", "alpha-2": "AS", "country-code": "016" },
    { "name": "Andorra", "alpha-2": "AD", "country-code": "020" },
    { "name": "Angola", "alpha-2": "AO", "country-code": "024" },
    { "name": "Anguilla", "alpha-2": "AI", "country-code": "660" },
    { "name": "Antarctica", "alpha-2": "AQ", "country-code": "010" },
    { "name": "Antigua and Barbuda", "alpha-2": "AG", "country-code": "028" },
    { "name": "Argentina", "alpha-2": "AR", "country-code": "032" },
    { "name": "Armenia", "alpha-2": "AM", "country-code": "051" },
    { "name": "Aruba", "alpha-2": "AW", "country-code": "533" },
    { "name": "Australia", "alpha-2": "AU", "country-code": "036" },
    { "name": "Austria", "alpha-2": "AT", "country-code": "040" },
    { "name": "Azerbaijan", "alpha-2": "AZ", "country-code": "031" },
    { "name": "Bahamas", "alpha-2": "BS", "country-code": "044" },
    { "name": "Bahrain", "alpha-2": "BH", "country-code": "048" },
    { "name": "Bangladesh", "alpha-2": "BD", "country-code": "050" },
    { "name": "Barbados", "alpha-2": "BB", "country-code": "052" },
    { "name": "Belarus", "alpha-2": "BY", "country-code": "112" },
    { "name": "Belgium", "alpha-2": "BE", "country-code": "056" },
    { "name": "Belize", "alpha-2": "BZ", "country-code": "084" },
    { "name": "Benin", "alpha-2": "BJ", "country-code": "204" },
    { "name": "Bermuda", "alpha-2": "BM", "country-code": "060" },
    { "name": "Bhutan", "alpha-2": "BT", "country-code": "064" },
    { "name": "Bolivia (Plurinational State of)", "alpha-2": "BO", "country-code": "068" },
    { "name": "Bonaire, Sint Eustatius and Saba", "alpha-2": "BQ", "country-code": "535" },
    { "name": "Bosnia and Herzegovina", "alpha-2": "BA", "country-code": "070" },
    { "name": "Botswana", "alpha-2": "BW", "country-code": "072" },
    { "name": "Bouvet Island", "alpha-2": "BV", "country-code": "074" },
    { "name": "Brazil", "alpha-2": "BR", "country-code": "076" },
    { "name": "British Indian Ocean Territory", "alpha-2": "IO", "country-code": "086" },
    { "name": "Brunei Darussalam", "alpha-2": "BN", "country-code": "096" },
    { "name": "Bulgaria", "alpha-2": "BG", "country-code": "100" },
    { "name": "Burkina Faso", "alpha-2": "BF", "country-code": "854" },
    { "name": "Burundi", "alpha-2": "BI", "country-code": "108" },
    { "name": "Cabo Verde", "alpha-2": "CV", "country-code": "132" },
    { "name": "Cambodia", "alpha-2": "KH", "country-code": "116" },
    { "name": "Cameroon", "alpha-2": "CM", "country-code": "120" },
    { "name": "Canada", "alpha-2": "CA", "country-code": "124" },
    { "name": "Cayman Islands", "alpha-2": "KY", "country-code": "136" },
    { "name": "Central African Republic", "alpha-2": "CF", "country-code": "140" },
    { "name": "Chad", "alpha-2": "TD", "country-code": "148" },
    { "name": "Chile", "alpha-2": "CL", "country-code": "152" },
    { "name": "China", "alpha-2": "CN", "country-code": "156" },
    { "name": "Christmas Island", "alpha-2": "CX", "country-code": "162" },
    { "name": "Cocos (Keeling) Islands", "alpha-2": "CC", "country-code": "166" },
    { "name": "Colombia", "alpha-2": "CO", "country-code": "170" },
    { "name": "Comoros", "alpha-2": "KM", "country-code": "174" },
    { "name": "Congo", "alpha-2": "CG", "country-code": "178" },
    { "name": "Congo, Democratic Republic of the", "alpha-2": "CD", "country-code": "180" },
    { "name": "Cook Islands", "alpha-2": "CK", "country-code": "184" },
    { "name": "Costa Rica", "alpha-2": "CR", "country-code": "188" },
    { "name": "Côte d'Ivoire", "alpha-2": "CI", "country-code": "384" },
    { "name": "Croatia", "alpha-2": "HR", "country-code": "191" },
    { "name": "Cuba", "alpha-2": "CU", "country-code": "192" },
    { "name": "Curaçao", "alpha-2": "CW", "country-code": "531" },
    { "name": "Cyprus", "alpha-2": "CY", "country-code": "196" },
    { "name": "Czechia", "alpha-2": "CZ", "country-code": "203" },
    { "name": "Denmark", "alpha-2": "DK", "country-code": "208" },
    { "name": "Djibouti", "alpha-2": "DJ", "country-code": "262" },
    { "name": "Dominica", "alpha-2": "DM", "country-code": "212" },
    { "name": "Dominican Republic", "alpha-2": "DO", "country-code": "214" },
    { "name": "Ecuador", "alpha-2": "EC", "country-code": "218" },
    { "name": "Egypt", "alpha-2": "EG", "country-code": "818" },
    { "name": "El Salvador", "alpha-2": "SV", "country-code": "222" },
    { "name": "Equatorial Guinea", "alpha-2": "GQ", "country-code": "226" },
    { "name": "Eritrea", "alpha-2": "ER", "country-code": "232" },
    { "name": "Estonia", "alpha-2": "EE", "country-code": "233" },
    { "name": "Eswatini", "alpha-2": "SZ", "country-code": "748" },
    { "name": "Ethiopia", "alpha-2": "ET", "country-code": "231" },
    { "name": "Falkland Islands (Malvinas)", "alpha-2": "FK", "country-code": "238" },
    { "name": "Faroe Islands", "alpha-2": "FO", "country-code": "234" },
    { "name": "Fiji", "alpha-2": "FJ", "country-code": "242" },
    { "name": "Finland", "alpha-2": "FI", "country-code": "246" },
    { "name": "France", "alpha-2": "FR", "country-code": "250" },
    { "name": "French Guiana", "alpha-2": "GF", "country-code": "254" },
    { "name": "French Polynesia", "alpha-2": "PF", "country-code": "258" },
    { "name": "French Southern Territories", "alpha-2": "TF", "country-code": "260" },
    { "name": "Gabon", "alpha-2": "GA", "country-code": "266" },
    { "name": "Gambia", "alpha-2": "GM", "country-code": "270" },
    { "name": "Georgia", "alpha-2": "GE", "country-code": "268" },
    { "name": "Germany", "alpha-2": "DE", "country-code": "276" },
    { "name": "Ghana", "alpha-2": "GH", "country-code": "288" },
    { "name": "Gibraltar", "alpha-2": "GI", "country-code": "292" },
    { "name": "Greece", "alpha-2": "GR", "country-code": "300" },
    { "name": "Greenland", "alpha-2": "GL", "country-code": "304" },
    { "name": "Grenada", "alpha-2": "GD", "country-code": "308" },
    { "name": "Guadeloupe", "alpha-2": "GP", "country-code": "312" },
    { "name": "Guam", "alpha-2": "GU", "country-code": "316" },
    { "name": "Guatemala", "alpha-2": "GT", "country-code": "320" },
    { "name": "Guernsey", "alpha-2": "GG", "country-code": "831" },
    { "name": "Guinea", "alpha-2": "GN", "country-code": "324" },
    { "name": "Guinea-Bissau", "alpha-2": "GW", "country-code": "624" },
    { "name": "Guyana", "alpha-2": "GY", "country-code": "328" },
    { "name": "Haiti", "alpha-2": "HT", "country-code": "332" },
    { "name": "Heard Island and McDonald Islands", "alpha-2": "HM", "country-code": "334" },
    { "name": "Holy See", "alpha-2": "VA", "country-code": "336" },
    { "name": "Honduras", "alpha-2": "HN", "country-code": "340" },
    { "name": "Hong Kong", "alpha-2": "HK", "country-code": "344" },
    { "name": "Hungary", "alpha-2": "HU", "country-code": "348" },
    { "name": "Iceland", "alpha-2": "IS", "country-code": "352" },
    { "name": "India", "alpha-2": "IN", "country-code": "356" },
    { "name": "Indonesia", "alpha-2": "ID", "country-code": "360" },
    { "name": "Iran (Islamic Republic of)", "alpha-2": "IR", "country-code": "364" },
    { "name": "Iraq", "alpha-2": "IQ", "country-code": "368" },
    { "name": "Ireland", "alpha-2": "IE", "country-code": "372" },
    { "name": "Isle of Man", "alpha-2": "IM", "country-code": "833" },
    { "name": "Israel", "alpha-2": "IL", "country-code": "376" },
    { "name": "Italy", "alpha-2": "IT", "country-code": "380" },
    { "name": "Jamaica", "alpha-2": "JM", "country-code": "388" },
    { "name": "Japan", "alpha-2": "JP", "country-code": "392" },
    { "name": "Jersey", "alpha-2": "JE", "country-code": "832" },
    { "name": "Jordan", "alpha-2": "JO", "country-code": "400" },
    { "name": "Kazakhstan", "alpha-2": "KZ", "country-code": "398" },
    { "name": "Kenya", "alpha-2": "KE", "country-code": "404" },
    { "name": "Kiribati", "alpha-2": "KI", "country-code": "296" },
    { "name": "Korea (Democratic People's Republic of)", "alpha-2": "KP", "country-code": "408" },
    { "name": "Korea, Republic of", "alpha-2": "KR", "country-code": "410" },
    { "name": "Kuwait", "alpha-2": "KW", "country-code": "414" },
    { "name": "Kyrgyzstan", "alpha-2": "KG", "country-code": "417" },
    { "name": "Lao People's Democratic Republic", "alpha-2": "LA", "country-code": "418" },
    { "name": "Latvia", "alpha-2": "LV", "country-code": "428" },
    { "name": "Lebanon", "alpha-2": "LB", "country-code": "422" },
    { "name": "Lesotho", "alpha-2": "LS", "country-code": "426" },
    { "name": "Liberia", "alpha-2": "LR", "country-code": "430" },
    { "name": "Libya", "alpha-2": "LY", "country-code": "434" },
    { "name": "Liechtenstein", "alpha-2": "LI", "country-code": "438" },
    { "name": "Lithuania", "alpha-2": "LT", "country-code": "440" },
    { "name": "Luxembourg", "alpha-2": "LU", "country-code": "442" },
    { "name": "Macao", "alpha-2": "MO", "country-code": "446" },
    { "name": "Madagascar", "alpha-2": "MG", "country-code": "450" },
    { "name": "Malawi", "alpha-2": "MW", "country-code": "454" },
    { "name": "Malaysia", "alpha-2": "MY", "country-code": "458" },
    { "name": "Maldives", "alpha-2": "MV", "country-code": "462" },
    { "name": "Mali", "alpha-2": "ML", "country-code": "466" },
    { "name": "Malta", "alpha-2": "MT", "country-code": "470" },
    { "name": "Marshall Islands", "alpha-2": "MH", "country-code": "584" },
    { "name": "Martinique", "alpha-2": "MQ", "country-code": "474" },
    { "name": "Mauritania", "alpha-2": "MR", "country-code": "478" },
    { "name": "Mauritius", "alpha-2": "MU", "country-code": "480" },
    { "name": "Mayotte", "alpha-2": "YT", "country-code": "175" },
    { "name": "Mexico", "alpha-2": "MX", "country-code": "484" },
    { "name": "Micronesia (Federated States of)", "alpha-2": "FM", "country-code": "583" },
    { "name": "Moldova, Republic of", "alpha-2": "MD", "country-code": "498" },
    { "name": "Monaco", "alpha-2": "MC", "country-code": "492" },
    { "name": "Mongolia", "alpha-2": "MN", "country-code": "496" },
    { "name": "Montenegro", "alpha-2": "ME", "country-code": "499" },
    { "name": "Montserrat", "alpha-2": "MS", "country-code": "500" },
    { "name": "Morocco", "alpha-2": "MA", "country-code": "504" },
    { "name": "Mozambique", "alpha-2": "MZ", "country-code": "508" },
    { "name": "Myanmar", "alpha-2": "MM", "country-code": "104" },
    { "name": "Namibia", "alpha-2": "NA", "country-code": "516" },
    { "name": "Nauru", "alpha-2": "NR", "country-code": "520" },
    { "name": "Nepal", "alpha-2": "NP", "country-code": "524" },
    { "name": "Netherlands", "alpha-2": "NL", "country-code": "528" },
    { "name": "New Caledonia", "alpha-2": "NC", "country-code": "540" },
    { "name": "New Zealand", "alpha-2": "NZ", "country-code": "554" },
    { "name": "Nicaragua", "alpha-2": "NI", "country-code": "558" },
    { "name": "Niger", "alpha-2": "NE", "country-code": "562" },
    { "name": "Nigeria", "alpha-2": "NG", "country-code": "566" },
    { "name": "Niue", "alpha-2": "NU", "country-code": "570" },
    { "name": "Norfolk Island", "alpha-2": "NF", "country-code": "574" },
    { "name": "North Macedonia", "alpha-2": "MK", "country-code": "807" },
    { "name": "Northern Mariana Islands", "alpha-2": "MP", "country-code": "580" },
    { "name": "Norway", "alpha-2": "NO", "country-code": "578" },
    { "name": "Oman", "alpha-2": "OM", "country-code": "512" },
    { "name": "Pakistan", "alpha-2": "PK", "country-code": "586" },
    { "name": "Palau", "alpha-2": "PW", "country-code": "585" },
    { "name": "Palestine, State of", "alpha-2": "PS", "country-code": "275" },
    { "name": "Panama", "alpha-2": "PA", "country-code": "591" },
    { "name": "Papua New Guinea", "alpha-2": "PG", "country-code": "598" },
    { "name": "Paraguay", "alpha-2": "PY", "country-code": "600" },
    { "name": "Peru", "alpha-2": "PE", "country-code": "604" },
    { "name": "Philippines", "alpha-2": "PH", "country-code": "608" },
    { "name": "Pitcairn", "alpha-2": "PN", "country-code": "612" },
    { "name": "Poland", "alpha-2": "PL", "country-code": "616" },
    { "name": "Portugal", "alpha-2": "PT", "country-code": "620" },
    { "name": "Puerto Rico", "alpha-2": "PR", "country-code": "630" },
    { "name": "Qatar", "alpha-2": "QA", "country-code": "634" },
    { "name": "Réunion", "alpha-2": "RE", "country-code": "638" },
    { "name": "Romania", "alpha-2": "RO", "country-code": "642" },
    { "name": "Russian Federation", "alpha-2": "RU", "country-code": "643" },
    { "name": "Rwanda", "alpha-2": "RW", "country-code": "646" },
    { "name": "Saint Barthélemy", "alpha-2": "BL", "country-code": "652" },
    { "name": "Saint Helena, Ascension and Tristan da Cunha", "alpha-2": "SH", "country-code": "654" },
    { "name": "Saint Kitts and Nevis", "alpha-2": "KN", "country-code": "659" },
    { "name": "Saint Lucia", "alpha-2": "LC", "country-code": "662" },
    { "name": "Saint Martin (French part)", "alpha-2": "MF", "country-code": "663" },
    { "name": "Saint Pierre and Miquelon", "alpha-2": "PM", "country-code": "666" },
    { "name": "Saint Vincent and the Grenadines", "alpha-2": "VC", "country-code": "670" },
    { "name": "Samoa", "alpha-2": "WS", "country-code": "882" },
    { "name": "San Marino", "alpha-2": "SM", "country-code": "674" },
    { "name": "Sao Tome and Principe", "alpha-2": "ST", "country-code": "678" },
    { "name": "Saudi Arabia", "alpha-2": "SA", "country-code": "682" },
    { "name": "Senegal", "alpha-2": "SN", "country-code": "686" },
    { "name": "Serbia", "alpha-2": "RS", "country-code": "688" },
    { "name": "Seychelles", "alpha-2": "SC", "country-code": "690" },
    { "name": "Sierra Leone", "alpha-2": "SL", "country-code": "694" },
    { "name": "Singapore", "alpha-2": "SG", "country-code": "702" },
    { "name": "Sint Maarten (Dutch part)", "alpha-2": "SX", "country-code": "534" },
    { "name": "Slovakia", "alpha-2": "SK", "country-code": "703" },
    { "name": "Slovenia", "alpha-2": "SI", "country-code": "705" },
    { "name": "Solomon Islands", "alpha-2": "SB", "country-code": "090" },
    { "name": "Somalia", "alpha-2": "SO", "country-code": "706" },
    { "name": "South Africa", "alpha-2": "ZA", "country-code": "710" },
    { "name": "South Georgia and the South Sandwich Islands", "alpha-2": "GS", "country-code": "239" },
    { "name": "South Sudan", "alpha-2": "SS", "country-code": "728" },
    { "name": "Spain", "alpha-2": "ES", "country-code": "724" },
    { "name": "Sri Lanka", "alpha-2": "LK", "country-code": "144" },
    { "name": "Sudan", "alpha-2": "SD", "country-code": "729" },
    { "name": "Suriname", "alpha-2": "SR", "country-code": "740" },
    { "name": "Svalbard and Jan Mayen", "alpha-2": "SJ", "country-code": "744" },
    { "name": "Sweden", "alpha-2": "SE", "country-code": "752" },
    { "name": "Switzerland", "alpha-2": "CH", "country-code": "756" },
    { "name": "Syrian Arab Republic", "alpha-2": "SY", "country-code": "760" },
    { "name": "Taiwan, Province of China", "alpha-2": "TW", "country-code": "158" },
    { "name": "Tajikistan", "alpha-2": "TJ", "country-code": "762" },
    { "name": "Tanzania, United Republic of", "alpha-2": "TZ", "country-code": "834" },
    { "name": "Thailand", "alpha-2": "TH", "country-code": "764" },
    { "name": "Timor-Leste", "alpha-2": "TL", "country-code": "626" },
    { "name": "Togo", "alpha-2": "TG", "country-code": "768" },
    { "name": "Tokelau", "alpha-2": "TK", "country-code": "772" },
    { "name": "Tonga", "alpha-2": "TO", "country-code": "776" },
    { "name": "Trinidad and Tobago", "alpha-2": "TT", "country-code": "780" },
    { "name": "Tunisia", "alpha-2": "TN", "country-code": "788" },
    { "name": "Turkey", "alpha-2": "TR", "country-code": "792" },
    { "name": "Turkmenistan", "alpha-2": "TM", "country-code": "795" },
    { "name": "Turks and Caicos Islands", "alpha-2": "TC", "country-code": "796" },
    { "name": "Tuvalu", "alpha-2": "TV", "country-code": "798" },
    { "name": "Uganda", "alpha-2": "UG", "country-code": "800" },
    { "name": "Ukraine", "alpha-2": "UA", "country-code": "804" },
    { "name": "United Arab Emirates", "alpha-2": "AE", "country-code": "784" },
    { "name": "United Kingdom of Great Britain and Northern Ireland", "alpha-2": "GB", "country-code": "826" },
    { "name": "United States of America", "alpha-2": "US", "country-code": "840" },
    { "name": "United States Minor Outlying Islands", "alpha-2": "UM", "country-code": "581" },
    { "name": "Uruguay", "alpha-2": "UY", "country-code": "858" },
    { "name": "Uzbekistan", "alpha-2": "UZ", "country-code": "860" },
    { "name": "Vanuatu", "alpha-2": "VU", "country-code": "548" },
    { "name": "Venezuela (Bolivarian Republic of)", "alpha-2": "VE", "country-code": "862" },
    { "name": "Viet Nam", "alpha-2": "VN", "country-code": "704" },
    { "name": "Virgin Islands (British)", "alpha-2": "VG", "country-code": "092" },
    { "name": "Virgin Islands (U.S.)", "alpha-2": "VI", "country-code": "850" },
    { "name": "Wallis and Futuna", "alpha-2": "WF", "country-code": "876" },
    { "name": "Western Sahara", "alpha-2": "EH", "country-code": "732" },
    { "name": "Yemen", "alpha-2": "YE", "country-code": "887" },
    { "name": "Zambia", "alpha-2": "ZM", "country-code": "894" },
    { "name": "Zimbabwe", "alpha-2": "ZW", "country-code": "716" }
];

const convertFromCountrieswithRegionalCodes2PopulationByCountry = {
    "Bolivia (Plurinational State of)": "Bolivia",
    "Brunei Darussalam": "Brunei",
    "Cape Verde": "Cabo Verde",
    "Congo, Democratic Republic of the": "DR Congo",
    "Czechia": "Czech Republic (Czechia)",
    "Falkland Islands (Malvinas)": "Falkland Islands",
    "Faroe Islands": "Faeroe Islands",
    "Holy See (Vatican City State)": "Holy See",
    "Iran (Islamic Republic of)": "Iran",
    "Korea (Democratic People's Republic of)": "North Korea",
    "Korea, Republic of": "South Korea",
    "Lao People's Democratic Republic": "Laos",
    "Macedonia, the Former Yugoslav Republic of": "North Macedonia",
    "Micronesia (Federated States of)": "Micronesia",
    "Myanmar": "Burma",
    "Moldova, Republic of": "Moldova",
    "Palestine, State of": "State of Palestine",
    "Russian Federation": "Russia",
    "Saint Barthélemy": "Saint Barthelemy",
    "Saint Helena, Ascension and Tristan da Cunha": "Saint Helena",
    "Saint Kitts and Nevis": "Saint Kitts & Nevis",
    "Saint Martin (French part)": "Saint Martin",
    "Saint Pierre and Miquelon": "Saint Pierre & Miquelon",
    "Saint Vincent and the Grenadines": "St. Vincent & Grenadines",
    "Sao Tome and Principe": "Sao Tome & Principe",
    "Sint Maarten (Dutch part)": "Sint Maarten",
    "Swaziland": "Eswatini",
    "Syrian Arab Republic": "Syria",
    "Taiwan, Province of China": "Taiwan",
    "Tanzania, United Republic of": "Tanzania",
    "Turks and Caicos Islands": "Turks and Caicos",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "United States of America": "United States",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands (British)": "British Virgin Islands",
    "Virgin Islands (U.S.)": "U.S. Virgin Islands",
    "Wallis and Futuna": "Wallis & Futuna",
}

const excludedNoPopulation = _.sortedUniq(_.sortBy([
    /* "Burma", // added manually, cf. "Myanmar" above */
    "Diamond Princess", // https://en.wikipedia.org/wiki/Diamond_Princess_(ship)
    /* "Kosovo", // added manually, see above */
    "MS Zaandam" // https://en.wikipedia.org/wiki/MS_Zaandam
]));

// use http://covid.aequologica.net/utils/noCovidData.html 
// to check from time to time if new countries are added to JHU data
export const excludedNoCovidData = _.sortedUniq(_.sortBy([
    "American Samoa",
    "Anguilla",
    "Aruba",
    "Bermuda",
    "British Virgin Islands",
    "Caribbean Netherlands",
    "Cayman Islands",
    "Channel Islands",
    "Cook Islands",
    "Curaçao",
    "Faeroe Islands",
    "Falkland Islands",
    "French Guiana",
    "French Polynesia",
    "Gibraltar",
    "Greenland",
    "Guadeloupe",
    "Guam",
    "Hong Kong",
    "Isle of Man",
    "Kiribati",
    "Macao",
    "Marshall Islands",
    "Martinique",
    "Mayotte",
    "Micronesia",
    "Montserrat",
    "Myanmar",
    "Nauru",
    "New Caledonia",
    "Niue",
    "North Korea",
    "Northern Mariana Islands",
    "Palau",
    "Puerto Rico",
    "Réunion",
    "Saint Barthelemy",
    "Saint Helena",
    "Saint Martin",
    "Saint Pierre & Miquelon",
    "Samoa",
    "Sint Maarten",
    "Solomon Islands",
    "Tokelau",
    "Tonga",
    "Turkmenistan",
    "Turks and Caicos",
    "Tuvalu",
    "U.S. Virgin Islands",
    "Vanuatu",
    "Wallis & Futuna",
]));

// add country code to populationByCountryRaw
const notfound = [];
const notfound2 = [];
const notfound3 = [];
const notfound4 = [];
_.each(countrieswithRegionalCodes, (item) => {
    const found = _.find(populationByCountryRaw, (country) => {
        const countray = convertFromCountrieswithRegionalCodes2PopulationByCountry[item.name] || item.name;
        return country.name === countray;
    });
    if (found) {
        found.code = item["alpha-2"];
    } else {
        notfound.push(item);
    }
});
const isExcluded = name => {
    if (-1 !== _.sortedIndexOf(excludedNoPopulation, name)) {
        notfound3.push(name);
        return true;
    }
    if (-1 !== _.sortedIndexOf(excludedNoCovidData, name)) {
        notfound4.push(name);
        return true;
    }
    return false;
};
const populationByCountryWorld = [];
populationByCountryRaw.forEach(p => {
    if (!p.code) {
        notfound2.push(p);
        return;
    } else {
        if (isExcluded(p.name)) {
            return;
        }
    }
    populationByCountryWorld.push(p);
});


// console.log("country name not found in populationByCountryRaw", notfound);
// console.log("country code not found in countrieswithRegionalCodes", notfound2);
// console.log("country population not found", notfound3);
// console.log("country covid data not found", notfound4);

export const code2name = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}
// https://datausa.io/api/data?drilldowns=State&measures=Population&year=latest
const populationByCountryUSRaw = [
    { "ID State": "04000US30", "State": "Montana", "ID Year": 2018, "Year": "2018", "Population": 1062305, "Slug State": "montana" },
    { "ID State": "04000US01", "State": "Alabama", "ID Year": 2018, "Year": "2018", "Population": 4887871, "Slug State": "alabama" },
    { "ID State": "04000US04", "State": "Arizona", "ID Year": 2018, "Year": "2018", "Population": 7171646, "Slug State": "arizona" },
    { "ID State": "04000US05", "State": "Arkansas", "ID Year": 2018, "Year": "2018", "Population": 3013825, "Slug State": "arkansas" },
    { "ID State": "04000US06", "State": "California", "ID Year": 2018, "Year": "2018", "Population": 39557045, "Slug State": "california" },
    { "ID State": "04000US08", "State": "Colorado", "ID Year": 2018, "Year": "2018", "Population": 5695564, "Slug State": "colorado" },
    { "ID State": "04000US09", "State": "Connecticut", "ID Year": 2018, "Year": "2018", "Population": 3572665, "Slug State": "connecticut" },
    { "ID State": "04000US10", "State": "Delaware", "ID Year": 2018, "Year": "2018", "Population": 967171, "Slug State": "delaware" },
    { "ID State": "04000US11", "State": "District of Columbia", "ID Year": 2018, "Year": "2018", "Population": 702455, "Slug State": "district-of-columbia" },
    { "ID State": "04000US12", "State": "Florida", "ID Year": 2018, "Year": "2018", "Population": 21299325, "Slug State": "florida" },
    { "ID State": "04000US13", "State": "Georgia", "ID Year": 2018, "Year": "2018", "Population": 10519475, "Slug State": "georgia" },
    { "ID State": "04000US15", "State": "Hawaii", "ID Year": 2018, "Year": "2018", "Population": 1420491, "Slug State": "hawaii" },
    { "ID State": "04000US16", "State": "Idaho", "ID Year": 2018, "Year": "2018", "Population": 1754208, "Slug State": "idaho" },
    { "ID State": "04000US17", "State": "Illinois", "ID Year": 2018, "Year": "2018", "Population": 12741080, "Slug State": "illinois" },
    { "ID State": "04000US18", "State": "Indiana", "ID Year": 2018, "Year": "2018", "Population": 6691878, "Slug State": "indiana" },
    { "ID State": "04000US19", "State": "Iowa", "ID Year": 2018, "Year": "2018", "Population": 3156145, "Slug State": "iowa" },
    { "ID State": "04000US20", "State": "Kansas", "ID Year": 2018, "Year": "2018", "Population": 2911510, "Slug State": "kansas" },
    { "ID State": "04000US21", "State": "Kentucky", "ID Year": 2018, "Year": "2018", "Population": 4468402, "Slug State": "kentucky" },
    { "ID State": "04000US22", "State": "Louisiana", "ID Year": 2018, "Year": "2018", "Population": 4659978, "Slug State": "louisiana" },
    { "ID State": "04000US23", "State": "Maine", "ID Year": 2018, "Year": "2018", "Population": 1338404, "Slug State": "maine" },
    { "ID State": "04000US24", "State": "Maryland", "ID Year": 2018, "Year": "2018", "Population": 6042718, "Slug State": "maryland" },
    { "ID State": "04000US25", "State": "Massachusetts", "ID Year": 2018, "Year": "2018", "Population": 6902149, "Slug State": "massachusetts" },
    { "ID State": "04000US26", "State": "Michigan", "ID Year": 2018, "Year": "2018", "Population": 9995915, "Slug State": "michigan" },
    { "ID State": "04000US27", "State": "Minnesota", "ID Year": 2018, "Year": "2018", "Population": 5611179, "Slug State": "minnesota" },
    { "ID State": "04000US28", "State": "Mississippi", "ID Year": 2018, "Year": "2018", "Population": 2986530, "Slug State": "mississippi" },
    { "ID State": "04000US29", "State": "Missouri", "ID Year": 2018, "Year": "2018", "Population": 6126452, "Slug State": "missouri" },
    { "ID State": "04000US02", "State": "Alaska", "ID Year": 2018, "Year": "2018", "Population": 737438, "Slug State": "alaska" },
    { "ID State": "04000US31", "State": "Nebraska", "ID Year": 2018, "Year": "2018", "Population": 1929268, "Slug State": "nebraska" },
    { "ID State": "04000US32", "State": "Nevada", "ID Year": 2018, "Year": "2018", "Population": 3034392, "Slug State": "nevada" },
    { "ID State": "04000US33", "State": "New Hampshire", "ID Year": 2018, "Year": "2018", "Population": 1356458, "Slug State": "new-hampshire" },
    { "ID State": "04000US34", "State": "New Jersey", "ID Year": 2018, "Year": "2018", "Population": 8908520, "Slug State": "new-jersey" },
    { "ID State": "04000US35", "State": "New Mexico", "ID Year": 2018, "Year": "2018", "Population": 2095428, "Slug State": "new-mexico" },
    { "ID State": "04000US36", "State": "New York", "ID Year": 2018, "Year": "2018", "Population": 19542209, "Slug State": "new-york" },
    { "ID State": "04000US37", "State": "North Carolina", "ID Year": 2018, "Year": "2018", "Population": 10383620, "Slug State": "north-carolina" },
    { "ID State": "04000US38", "State": "North Dakota", "ID Year": 2018, "Year": "2018", "Population": 760077, "Slug State": "north-dakota" },
    { "ID State": "04000US39", "State": "Ohio", "ID Year": 2018, "Year": "2018", "Population": 11689442, "Slug State": "ohio" },
    { "ID State": "04000US40", "State": "Oklahoma", "ID Year": 2018, "Year": "2018", "Population": 3943079, "Slug State": "oklahoma" },
    { "ID State": "04000US41", "State": "Oregon", "ID Year": 2018, "Year": "2018", "Population": 4190713, "Slug State": "oregon" },
    { "ID State": "04000US42", "State": "Pennsylvania", "ID Year": 2018, "Year": "2018", "Population": 12807060, "Slug State": "pennsylvania" },
    { "ID State": "04000US44", "State": "Rhode Island", "ID Year": 2018, "Year": "2018", "Population": 1057315, "Slug State": "rhode-island" },
    { "ID State": "04000US45", "State": "South Carolina", "ID Year": 2018, "Year": "2018", "Population": 5084127, "Slug State": "south-carolina" },
    { "ID State": "04000US46", "State": "South Dakota", "ID Year": 2018, "Year": "2018", "Population": 882235, "Slug State": "south-dakota" },
    { "ID State": "04000US47", "State": "Tennessee", "ID Year": 2018, "Year": "2018", "Population": 6770010, "Slug State": "tennessee" },
    { "ID State": "04000US48", "State": "Texas", "ID Year": 2018, "Year": "2018", "Population": 28701845, "Slug State": "texas" },
    { "ID State": "04000US49", "State": "Utah", "ID Year": 2018, "Year": "2018", "Population": 3161105, "Slug State": "utah" },
    { "ID State": "04000US50", "State": "Vermont", "ID Year": 2018, "Year": "2018", "Population": 626299, "Slug State": "vermont" },
    { "ID State": "04000US51", "State": "Virginia", "ID Year": 2018, "Year": "2018", "Population": 8517685, "Slug State": "virginia" },
    { "ID State": "04000US53", "State": "Washington", "ID Year": 2018, "Year": "2018", "Population": 7535591, "Slug State": "washington" },
    { "ID State": "04000US54", "State": "West Virginia", "ID Year": 2018, "Year": "2018", "Population": 1805832, "Slug State": "west-virginia" },
    { "ID State": "04000US55", "State": "Wisconsin", "ID Year": 2018, "Year": "2018", "Population": 5813568, "Slug State": "wisconsin" },
    { "ID State": "04000US56", "State": "Wyoming", "ID Year": 2018, "Year": "2018", "Population": 577737, "Slug State": "wyoming" },
    { "ID State": "04000US72", "State": "Puerto Rico", "ID Year": 2018, "Year": "2018", "Population": 3195153, "Slug State": "puerto-rico" }
];

export const populationByCountryUS = [];
populationByCountryUSRaw.forEach(p => {
    populationByCountryUS.push({
        name: p.State, 
        count: p.Population, 
        code: _.findKey(code2name, _.partial(_.isEqual, p.State)),
    });
});
console.log(populationByCountryUS);

export const populationByCountry = {
    world: populationByCountryWorld,
    usa: populationByCountryUS,
};
